config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
]

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.add, name='add'),
    path('delete/<int:id>', views.delete, name='delete'),
]

todo/models.py
from django.db import models

# Create your models here.
class ToDoData(models.Model):
    title = models.CharField(max_length=100)

todo/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import ToDoData

# Create your views here.
def index(request):
    tasks = ToDoData.objects.all()
    return render(request, 'todo/list.html', {
        'tasks': tasks
    })

def add(request):
    if request.method == 'POST':
        title = request.POST['title']
        ToDoData.objects.create(title=title)
        return redirect('todo:index')
    return render(request, 'todo/add.html')

def delete(request, id):
    ToDoData.objects.get(id=id).delete()
    return redirect('todo:index')

todo/templates/todo/add.html
{% extends "todo/layout.html" %}
{% load static %}
{% block content %}
    <main>
        <h1>To Do List</h1>
        <a href="{% url 'todo:index' %}">トップ</a>
        <form action="" method="post">
            {% csrf_token %}
            <input type="text" name="title">
            <button type="submit">追加</button>
        </form>
    </main>
{% endblock content %}

todo/templates/todo/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>To Do List</title>
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>

todo/templates/todo/list.html
{% extends "todo/layout.html" %}
{% load static %}
{% block content %}
    <main>
        <h1>To Do List</h1>
        <a href="{% url 'todo:add' %}">追加</a>
        {% for task in tasks %}
            <div class="task" style="display: inline-block; width: 100%; margin-top: 30px">
                <p style="width: fit-content;">{{ task.title }}</p>
                <form action="{% url 'todo:delete' task.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit">完了</button>
                </form>
            </div>
        {% empty %}
            <p>タスクはありません。</p>
        {% endfor %}
    </main>
{% endblock content %}